In [1]:
import numpy as np

In [2]:
dummy_arrays  = np.zeros((10,100,100))
dummy_arrays.shape

(10, 100, 100)

In [3]:
array_list = [a for a in dummy_arrays]


In [14]:
k = ["A","B","C"]
dict = {kn:array_list.copy() for kn in k}
dict["D"] = ["Berk"]*10
dict

{'A': [array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]),
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]),
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]),
  array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0.,

In [15]:
base = "test_npz"
np.save(base+"_seg.npy", dict)

In [16]:
fname = base+"_seg.npy"
dat = np.load(fname, allow_pickle=True)

In [17]:
dat.item()["D"]

['Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk',
 'Berk']

In [21]:
import my_io

In [24]:
dir(io)

['BlockingIOError',
 'BufferedIOBase',
 'BufferedRWPair',
 'BufferedRandom',
 'BufferedReader',
 'BufferedWriter',
 'BytesIO',
 'DEFAULT_BUFFER_SIZE',
 'FileIO',
 'IOBase',
 'IncrementalNewlineDecoder',
 'RawIOBase',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'StringIO',
 'TextIOBase',
 'TextIOWrapper',
 'UnsupportedOperation',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_io',
 'abc',
 'open',
 'open_code',
 'text_encoding']

In [18]:
{"A":1} | {"B":2}

{'A': 1, 'B': 2}